[build]
  base = "frontend"            # Base directory for the build process
  publish = "build"   # Directory where build artifacts are generated
  command = "npm install && npm run build"  # Build command

[dev]
  command = "npm start"        # Command to run your dev server locally (optional)
  port = 3000                  # Port for the local development server (optional)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
